// <auto-generated />
using JarvisGoogleAPI.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JarvisGoogleAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210314202340_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JarvisGoogleAPI.Domain.Entities.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SystemName = "process_start",
                            UserName = "запусти"
                        },
                        new
                        {
                            Id = 2,
                            SystemName = "process_kill",
                            UserName = "закрой"
                        },
                        new
                        {
                            Id = 3,
                            SystemName = "browser_find",
                            UserName = "найди"
                        },
                        new
                        {
                            Id = 4,
                            SystemName = "jarvis_shutdown",
                            UserName = "умри"
                        });
                });

            modelBuilder.Entity("JarvisGoogleAPI.Domain.Entities.ProcName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SystemName = "calc",
                            UserName = "калькулятор"
                        },
                        new
                        {
                            Id = 2,
                            SystemName = "devenv",
                            UserName = "студию"
                        },
                        new
                        {
                            Id = 3,
                            SystemName = "opera",
                            UserName = "браузер"
                        },
                        new
                        {
                            Id = 4,
                            SystemName = "notepad",
                            UserName = "блокнот"
                        },
                        new
                        {
                            Id = 5,
                            SystemName = "mspaint",
                            UserName = "рисование"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
